Break auto-start early.

diff --git a/site-cookbooks/basenode/templates/default/autostart.sh.erb b/site-cookbooks/basenode/templates/default/autostart.sh.erb
--- a/site-cookbooks/basenode/templates/default/autostart.sh.erb
+++ b/site-cookbooks/basenode/templates/default/autostart.sh.erb
@@ -25,6 +25,10 @@ for FILE in $AUTOSTART_FILES; do
 	echo ">> Running autostart file $FILE" >> $LOGFILE
 
 	./$FILE >> $LOGFILE 2>&1
+	if [ $? -ne 0 ]; then
+		echo ">> Quitting autostart early due to failure" >> $LOGFILE
+		break
+	fi
 done
 
 
